name: Package

on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
    steps:
      - name: Install Subversion
        run: sudo apt-get update && sudo apt-get install subversion

      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Package and release
        uses: BigWigsMods/packager@v2
        
