name: Package-WotLK

on:
  push:
    tags:
      - '**'

jobs:
  release-wotlk:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Package and release
        uses: BigWigsMods/packager@v2
        with:
            args: -g wrath
